name: 02 - Workflow Events 

on: 
    pull_request:
    workflow_dispatch: 

jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Mostre os Triggers
              run: echo "Eu fui engatilhado(triggered) por um(a) ${{ github.event_name }} event."
