name: 02 - Workflow Events 

on: push

jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Mostre os Triggers
              run: echo "Eu fui engatilhado(triggered) por a(n) ${{ github.event_name }} event."
