name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{inputs.debug}}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env:
    MY_WORKFLOW_VAR: "Workflow"
    MY_OVERWRITTEN_VAR: "Workflow"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job"
            MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Mostra as informações
              run: |
                echo "Nome do Evento: ${{ github.event_name }}"
                echo "Referencia: ${{ github.ref }} "
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{github.workflow}}"
                echo "RUN ID: ${{ github.run_id }}"
                echo "Run number ${{github.run_number}} "
            - name: Retrieve Variable
              run: | 
                echo "Valor da variável: ${{ vars.MY_VAR }}"
            - name: print das variáveis de ambiente
              env:
                MY_OVERWRITTEN_VAR: "step"
              run: |
                echo "Workflow env:  ${{env.MY_WORKFLOW_VAR}}"
                echo "Overitten env:  ${{env.MY_OVERWRITTEN_VAR}}"
            - name: print das variáveis
              run: |
                echo "Workflow env:  ${{env.MY_WORKFLOW_VAR}}"
                echo "Overitten env:  ${{env.MY_OVERWRITTEN_VAR}}"          