name: 09 - Using Functions

on:
    pull_request:
    workflow_dispatch:

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo "${{ github.event.pull_request.title }}"
            
            - name: Print PR labels
              run: |
                cat << EOF
                ${{ toJson(github.event.pull_request.labels)}}
                EOF

            - name: Bug step
              if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix' )}}
              run: echo "eu sou um bug fix"

            - name: Sleep
              run: sleep 10

            - name: Failing step
              run: exit 1

            - name: I will be skipped
              if: ${{ success() }}
              run: echo "Eu vou aparecer se o passo anterior for um sucesso."

            - name: I will execute
              if: ${{ failure() }}
              run: echo "Eu vou aparecer se algum passo anterior falhar."
            
            - name: I will execute
              if: ${{ !cancelled() }}
              run: echo "Eu vou aparecer sempre, exceto quando o workflow é cancelado."

            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "Eu vou aparecer quando o workflow é cancelado."