name: 09 - Using Functions

on:
    workflow_dispatch:

jobs: 
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: I will be execute
              if: ${{ success() }}
              run: echo "Eu vou aparecer se o passo anterior for um sucesso."

            - name: I will be skipped
              if: ${{ failure() }}
              run: echo "Eu vou aparecer se algum passo anterior falhar."
            
            - name: I will execute
              if: ${{ !cancelled() }}
              run: echo "Eu vou aparecer sempre, exceto quando o workflow é cancelado."

            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "Eu vou aparecer quando o workflow é cancelado."