name: 10 - Controlling the Execution Flow

on:
    workflow_dispatch:
        inputs:
          pass-unit-tests:
            type: boolean
            description: Quando os unit tests vao passar ou não
            default: true

jobs:
    lint-build:
      runs-on: ubuntu-latest
      steps:
        - name: Lint and build
          run: echo "Linting and building project"

    unit-tests:
       runs-on: ubuntu-latest
       steps: 
        - name: Rodando testes de unidade
          run: echo "Rodando os testes..."
        - name: Teste de falha
          if: ${{ !inputs.pass-unit-tests }}
          run: exit 1

    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-tests
        steps:
            - name: Deploying para o nonprod
              run: echo "Deploy para o nonprod"

    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Rodando testes E2E
              run: echo "Rodando testes E2E"
    
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Rodando testes load
              run: echo "Rodando testes load"

    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying para o prod
              run: echo "Deploying para o prod..."